from typing import Protocol, overload


class Transport(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def send(self, data: bytes | str) -> None: ...
    @overload
    async def recv(self) -> bytes | str: ...
    @overload
    async def recv(self, n: int) -> bytes | str: ...
    async def recv(self, n: int | None = None) -> bytes | str: ...
    @property
    def connected(self) -> bool: ...
