from typing import Protocol, runtime_checkable

from .models import SessionInfo


@runtime_checkable
class StoreProtocol(Protocol):
    async def save_session(self, session_info: SessionInfo) -> None: ...
    async def update_token(self, old_token: str, new_token: str) -> None: ...
    async def load_session(self) -> SessionInfo | None: ...
    async def load_session_by_device_id(self, device_id: str) -> SessionInfo | None: ...
    async def load_session_by_phone(self, phone: str) -> SessionInfo | None: ...
    async def delete_session(self, token: str) -> None: ...
    async def close(self) -> None: ...
